#!/usr/bin/python3 -OO
# Copyright 2007-2026 by The SABnzbd-Team (sabnzbd.org)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.

"""
tests.test_conformance_vectors - Conformance checks over the vendored yEnc
encryption standards v1.2 test vector fixtures.

The fixtures in tests/data/test-vectors/ are byte-identical copies of the
canonical set generated by the standards repository (yenc-encryption-standards/
test-vectors/, sha256-pinned by manifest.json). This module validates that the
vendored copies still match the manifest and exercises the fixture-driven
contract shapes that SABnzbd's encrypted-yEnc support must honour:

- manifest sha256 sync for every vendored vector file
- VEC-05 malformed input rejection shapes (error class, rejection stage,
  zero-output guarantee, provider-failover eligibility)
- VEC-06 NZB meta tag expectations (``yenc_encrypted`` and ``password`` meta
  presence on encrypted releases; absent on ordinary NZBs)
- VEC-07 segmentIndex allocation skip rules (0x0A/0x0D forbidden in the
  4-byte big-endian encoding)

All checks are pure stdlib: no crypto libraries are required at this stage,
and nothing is imported from outside this repository tree. The cryptographic
round-trip vectors are exercised in a later milestone, once the downloader
gains decrypt capability.
"""

import hashlib
import json
import os
import sys
from pathlib import Path

import pytest

TEST_VECTORS_DIR = Path(__file__).parent / "data" / "test-vectors"

VECTOR_FILES = (
    "argon2id.json",
    "body_encryption.json",
    "control_line_encryption.json",
    "index_allocation.json",
    "malformed_inputs.json",
    "nonce_tweak.json",
    "nzb_segment_identity.json",
)


def _load_fixture(name: str):
    with open(TEST_VECTORS_DIR / name, "r", encoding="utf-8") as fixture_file:
        return json.load(fixture_file)


@pytest.fixture(name="manifest")
def fixture_manifest() -> dict:
    return _load_fixture("manifest.json")


def test_vendored_fixtures_match_manifest(manifest: dict):
    """Every vendored vector file must hash to its manifest sha256 (v1.2 set)."""
    assert manifest["standard_version"] == "1.2"
    assert sorted(manifest["files"].keys()) == sorted(VECTOR_FILES)
    for name in VECTOR_FILES:
        with open(TEST_VECTORS_DIR / name, "rb") as fixture_file:
            digest = hashlib.sha256(fixture_file.read()).hexdigest()
        assert digest == manifest["files"][name]["sha256"], f"sha256 drift in {name}"


def test_malformed_inputs_rejection_shapes():
    """VEC-05: every malformed vector pins error class, stage and zero-output."""
    vectors = _load_fixture("malformed_inputs.json")["vectors"]
    assert len(vectors) == 46

    known_errors = {
        "UNSUPPORTED_CIPHER",
        "INVALID_TOKEN_COUNT",
        "INVALID_SALT_LENGTH",
        "INVALID_SALT_HEX",
        "INVALID_TAG_LENGTH",
        "INVALID_TAG_HEX",
        "ZERO_SEGMENT_INDEX",
        "INVALID_INDEX_LENGTH",
        "INVALID_INDEX_HEX",
        "UPPERCASE_HEX",
        "AUTHENTICATION_FAILURE",
        "INVALID_SALT_CHARACTER",
        "LINE_TOO_SHORT",
        "LINE_TRUNCATED",
        "FORBIDDEN_SEGMENT_INDEX_BYTE",
        "CONTROL_LINE_DECRYPT_FAILURE",
        "MISSING_ENCRYPTION_PROVENANCE",
        "INVALID_ENCRYPTION_PROVENANCE",
        "MISPLACED_ENCRYPTION_HEADER",
        "SALT_MISMATCH",
        "DUAL_INDEX_MISMATCH",
        "INVALID_WHITESPACE",
        "MISSING_PASSWORD",
        "METADATA_VALIDATION_BODY_ONLY",
    }
    for vector in vectors:
        assert vector["expected_error"] in known_errors
        assert vector["expected_rejection_stage"] in ("PROVIDER_FAILOVER", "METADATA_VALIDATION")
        assert vector["zero_output_required"] is True

    # Authentication failures must stay retryable: eligible for provider
    # failover and never released as final output.
    auth_failures = [v for v in vectors if v["expected_error"] == "AUTHENTICATION_FAILURE"]
    assert len(auth_failures) == 4
    for vector in auth_failures:
        assert vector["expected_rejection_stage"] == "PROVIDER_FAILOVER"
        assert vector["provider_failover_permitted"] is True
        assert vector["zero_output_required"] is True

    # Metadata-shape failures are job-level, never provider corruption.
    metadata_failures = [v for v in vectors if v["expected_rejection_stage"] == "METADATA_VALIDATION"]
    assert len(metadata_failures) == 4
    for vector in metadata_failures:
        assert vector["provider_failover_permitted"] is False


def test_nzb_meta_tag_expectations():
    """VEC-06: encrypted NZBs carry yenc_encrypted + password meta; plain NZBs don't."""
    vectors = _load_fixture("nzb_segment_identity.json")["vectors"]
    assert len(vectors) == 33

    encrypted = [v for v in vectors if v.get("is_encrypted")]
    unencrypted = [v for v in vectors if v.get("is_encrypted") is False]
    assert len(unencrypted) == 2

    for vector in encrypted:
        nzb_xml = vector["nzb_xml"]
        assert '<meta type="yenc_encrypted">true</meta>' in nzb_xml, vector["id"]
        assert '<meta type="password">' in nzb_xml, vector["id"]

    for vector in unencrypted:
        nzb_xml = vector["nzb_xml"]
        assert '<meta type="yenc_encrypted">' not in nzb_xml, vector["id"]
        assert '<meta type="password">' not in nzb_xml, vector["id"]
        # Unencrypted releases keep valid identity with no segmentIndex.
        assert vector["expected_valid"] is True
        for segment in vector["expected_segments"]:
            assert segment["segment_index"] is None


def test_index_allocation_skip_rules():
    """VEC-07: segmentIndex candidates containing 0x0A/0x0D in their 4-byte BE encoding are skipped."""
    vectors = _load_fixture("index_allocation.json")["vectors"]
    assert len(vectors) == 4

    for vector in vectors:
        candidate = vector["candidate_index"]
        encoded = candidate.to_bytes(4, "big")
        if vector["expected_error"] is None:
            assert b"\x0a" in encoded or b"\x0d" in encoded, vector["id"]
            assigned = vector["expected_assigned_index"]
            assigned_encoded = assigned.to_bytes(4, "big")
            assert b"\x0a" not in assigned_encoded, vector["id"]
            assert b"\x0d" not in assigned_encoded, vector["id"]
            assert assigned_encoded.hex() == vector["expected_index_hex"]
        else:
            pytest.fail(f"unexpected error expectation in {vector['id']}")

    # The forbidden sentinel: index 269 itself must never be assigned.
    forbidden = [v for v in vectors if v["candidate_index"] == 269]
    assert len(forbidden) == 1
    assert forbidden[0]["expected_assigned_index"] == 270


def test_index_allocation_reference_sequence():
    """The canonical skip examples keep stable expected assignments."""
    vectors = _load_fixture("index_allocation.json")["vectors"]
    by_id = {v["id"]: v for v in vectors}
    assert by_id["index-allocation-01-skip-10"]["expected_assigned_index"] == 11
    assert by_id["index-allocation-02-skip-13"]["expected_assigned_index"] == 14
    assert by_id["index-allocation-03-skip-266"]["expected_assigned_index"] == 267
    assert by_id["index-allocation-04-skip-269"]["expected_assigned_index"] == 270


if __name__ == "__main__":
    sys.exit(pytest.main([__file__]))
